Repository UX-Alkosto/webcomponents, pull requests merged in 2021-07, with the labels that each got.

#88 Actualización acordeón y k-icon
  .eslintignore
  components/acordeon/acordeon.js
  components/acordeon/css/index.js
  components/acordeon/index.js
  components/card/card.js
  components/card/css/index.js
  components/image/css/index.js
  components/image/image.js
  components/image/index.js
  components/slider/slider.js
  dist/components.js
  dist/glide.esm-0c52d1fc.js
  index.html
  index.js
  package-lock.json
  package.json
  rollup.config.js
Labels: css, enhancement

#93 Actualización de estilos y creación de tipo full-image-width para k-card
  .gitignore
  components/card/css/index.js
  dist/components.js
  dist/glide.esm-e472f27c.js
  index.html
  package-lock.json
  package.json
Labels: css

#94 Develop
  .gitignore
  assets/images/banner-1.png
  assets/images/banner-1@2x.png
  assets/images/banner-2.png
  assets/images/banner-2@2x.png
  assets/images/banner-3.png
  assets/images/banner-3@2x.png
  assets/images/img-familia-carro.png
  assets/images/product-1.png
  assets/images/product-1@2x.png
  assets/images/product-2.png
  assets/images/product-2@2x.png
  assets/images/product-3.png
  assets/images/product-3@2x.png
  components/card/css/index.js
  dist/components.js
  dist/glide.esm-0c52d1fc.js
  index.html
  package-lock.json
Labels: enhancement

#95 🐛 Fix typo on https urls
  index.html
Labels: bug

#96 ⚡️ Update images CDN path
  index.html
Labels: enhancement

#97 Updated SVG paths
  index.html
Labels: bug
