Repository UX-Alkosto/webcomponents, pull requests merged in 2021-05, with the labels that each got.

#10 Update dependencies 📦️
  components/banner/banner.js
  components/banner/css/index.js
  components/button/button.js
  components/button/css/index.js
  components/card/card.js
  components/card/css/index.js
  components/common/index.js
  components/grid/css/index.js
  components/grid/grid.js
  components/icon/css/index.js
  components/icon/icon.js
  components/image/css/index.js
  components/image/image.js
  components/link/css/index.js
  components/link/link.js
  components/slider/css/core.js
  components/slider/css/index.js
  components/slider/css/theme.js
  components/slider/slider.js
  dist/components.js
  package-lock.json
  package.json
Labels: dependencies

#29 Test
  dist/components.js
  package-lock.json
Labels: css

#31 Added mobile and desktop options for slider web component
  components/slider/css/theme.js
  components/slider/slider.js
  dist/components.js
  dist/glide.esm-f3f83750.js
  index.html
  package-lock.json
  package.json
Labels: enhancement

#35 Develop
  components/common/index.js
  dist/components.js
  dist/glide.esm-5eb52aa8.js
  package-lock.json
  package.json
Labels: css
