Repository UX-Alkosto/webcomponents, pull requests merged in 2021-12, with the labels that each got.

#236 Develop
  dist/components.js
  dist/glide.esm-b11ddb98.js
  dist/glide.esm-e58a4a0d.js
  karma.config.cjs
  package-lock.json
  package.json
Labels: dependencies

#243 Cambio margen k-card icon-item
  components/card/css/index.js
  dist/components.js
  dist/glide.esm-b11ddb98.js
  dist/glide.esm-f05ae0c4.js
  package-lock.json
  package.json
Labels: css

#244 Refactor JS to load components as modules
  dist/components.js
  dist/glide.esm-c886588c.js
  dist/glide.esm-f05ae0c4.js
  dist/index-07ddef91.js
  dist/index-0f5348ab.js
  dist/index-35284ef8.js
  dist/index-847e8551.js
  dist/index-a5b52dd4.js
  dist/index-b06a32a0.js
  dist/index-c252ae9d.js
  dist/index-c272d4cc.js
  dist/index-e43e37b6.js
  dist/index-f25f563d.js
  index.js
  package-lock.json
  package.json
  rollup.config.js
Labels: enhancement, npm, performance
